version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=teamcity_password
      - POSTGRES_USER=teamcity_user
      - POSTGRES_DB=teamcity_db
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - ./buildserver_pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432

  teamcity-server:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    ports:
      - "8111:8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./logs:/opt/teamcity/logs
    depends_on:
      - db

  teamcity-agent-android-1:
    image: teamcity-agent-custom-android
    privileged: true
    volumes:
      - ./agents/android/1/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start

  teamcity-agent-android-2:
    image: teamcity-agent-custom-android
    privileged: true
    volumes:
      - ./agents/android/2/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start

  teamcity-agent-android-3:
    image: teamcity-agent-custom-android
    privileged: true
    volumes:
      - ./agents/android/3/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start
